name: Main

on:
  push:
    branches:
      - master
jobs:
  install-build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          npm install
          npm install react
      - name: Build package
        run: npm run build
      - name: Run tests
        run: npm run test
      - name: Configure CI Git User
        run: |
          git remote rm origin
          git remote add origin "https://$USER_NAME:$GITHUB_PERSONAL_ACCESS_TOKEN@github.com/cchanxzy/testing-workflow.git"
          git fetch origin
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
        env:
          GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.GITHUB_PERSONAL_ACCESS_TOKEN }}
          USER_NAME: ${{ secrets.USER_NAME }}
      - name: Prepare new release
        run: |
          npm run release
          git push --follow-tags origin HEAD:master
  release:
    needs: install-build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
